require 'test/unit'
require './test/error.rb'
require './test/compound.rb'
require './test/task.rb'
require './test/feature.rb'
require './test/dataset.rb'
require './test/algorithm.rb'
require './test/model.rb'
